export const AppIcons = {
  arrow_right: require('../../../src/assets/icons/round-arrow_right.png'),
  google: require('../../../src/assets/icons/google.png'),
  facebook: require('../../../src/assets/icons/facebook.png'),
  home: require('../../../src/assets/icons/home.png'),
  profile: require('../../../src/assets/icons/profile.png'),
  shopping_cart: require('../../../src/assets/icons/shopping_cart.png'),
  bag: require('../../../src/assets/icons/bag.png'),
  heart: require('../../../src/assets/icons/heart.png'),
  home_active: require('../../../src/assets/icons/home_active.png'),
  profile_active: require('../../../src/assets/icons/profile_active.png'),
  shopping_cart_active: require('../../../src/assets/icons/shopping_cart_active.png'),
  bag_active: require('../../../src/assets/icons/bag_active.png'),
  heart_active: require('../../../src/assets/icons/heart_active.png'),
  heart_small: require('../../../src/assets/icons/heart_small.png'),
  heart_small_active: require('../../../src/assets/icons/heart_small_active.png'),
  star: require('../../../src/assets/icons/star.png'),
  search: require('../../../src/assets/icons/search.png'),
  left_arrow: require('../../../src/assets/icons/left_arrow.png'),
  filter: require('../../../src/assets/icons/filter.png'),
  layout: require('../../../src/assets/icons/layout.png'),
  sorting_arrow: require('../../../src/assets/icons/sorting_arrow.png'),
};
export const AppImages = {
  big_banner: require('../../../src/assets/images/big_banner.png'),
  small_banner: require('../../../src/assets/images/small_banner.png'),
  black: require('../../../src/assets/images/black.png'),
  main: require('../../../src/assets/images/main.png'),
  men_hat: require('../../../src/assets/images/men_hat.png'),
};
