export const ScreenNames = {
  loginScreen: 'LoginScreen',
  signupScreen: 'SignupScreen',
  homeScreen: 'HomeScreen',
  forgotScreen: 'ForgotScreen',
  homeTab: 'HomeTab',
  shopTab: 'ShopTab',
  bagTab: 'BagTab',
  favoriteTab: 'FavoriteTab',
  profileTab: 'ProfileTab',
  mainTab: 'MainTab',
  categoryScreen: 'CategoryScreen',
  allCategory: 'AllCategory',
  catalogScreen: 'CatalogScreen',
  productCardScreen: 'ProductCardScreen',
  cartScreen: 'CartScreen',
  checkoutScreen: 'CheckoutScreen',
  paymentScreen: 'PaymentScreen',
  shippingScreen: 'ShippingScreen',
  profileScreen: 'ProfileScreen',
  settingScreen: 'SettingScreen',
  orderScreen: 'OrderScreen',
  orderDetailScreen: 'OrderDetailScreen',
  ratingScreen: 'RatingScreen',
  brandScreen: 'BrandScreen',
};
