export const ScreenNames = {
  loginScreen: 'LoginScreen',
  signupScreen: 'SignupScreen',
  homeScreen: 'HomeScreen',
  forgotScreen: 'ForgotScreen',
  homeTab: 'HomeTab',
  shopTab: 'ShopTab',
  bagTab: 'BagTab',
  favoriteTab: 'FavoriteTab',
  profileTab: 'ProfileTab',
  mainTab: 'MainTab',
  categoryScreen: 'CategoryScreen',
  allCategory: 'AllCategory',
  catalogScreen: 'CatalogScreen',
  productCartScreen: 'ProductCartScreen',
  cartScreen: 'CartScreen',
};
